const C=window.PTD_CONFIG;const sb=supabase.createClient(C.supabaseUrl,C.supabasePublishableKey,{auth:{persistSession:true,detectSessionInUrl:true}});let product,sources=[],chart,days=30;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const euro=v=>v==null?'–':new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(v);const date=v=>v?new Intl.DateTimeFormat('de-DE',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'Noch nicht geprüft';
const logos={"PlayStation Direct DE":"https://cdn.simpleicons.org/playstation/0070D1","Amazon.de":"https://cdn.simpleicons.org/amazon/FF9900","MediaMarkt DE":"https://cdn.simpleicons.org/mediamarkt/DF0000","Saturn DE":"https://cdn.simpleicons.org/saturn/0066B3","Alternate DE":"https://www.google.com/s2/favicons?domain=alternate.de&sz=128","Expert DE":"https://www.google.com/s2/favicons?domain=expert.de&sz=128","Geizhals DE":"https://www.google.com/s2/favicons?domain=geizhals.de&sz=128","Idealo DE":"https://cdn.simpleicons.org/idealo/FF6600"};
function toast(x){$('#toast').textContent=x;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
async function load(){const {data:ps,error}=await sb.from('products').select('*').eq('active',true).limit(1);if(error||!ps?.length){$('#systemStatus').textContent='Keine Produktkonfiguration';return}product=ps[0];const {data:src}=await sb.from('product_sources').select('*,providers(*)').eq('product_id',product.id).order('providers(name)');sources=src||[];render();await loadHistory()}
function render(){const valid=sources.filter(x=>x.availability==='available'&&x.last_price!=null);const best=valid.sort((a,b)=>a.last_price-b.last_price)[0];$('#heroPrice').textContent=best?euro(best.last_price):'Kein Treffer';$('#heroText').textContent=best?`${best.providers.name} · verfügbar`:'Derzeit kein bestätigtes Angebot';$('#alertPrice').textContent=euro(product.alert_price);$('#targetPrice').textContent=euro(product.target_price);const newest=sources.map(x=>x.last_checked_at).filter(Boolean).sort().pop();$('#lastUpdated').textContent=date(newest);$('#providerCount').textContent=`${sources.length} Quellen`;
$('#providerGrid').innerHTML=sources.map(x=>{const a=x.availability||'unknown';const label=a==='available'?'Verfügbar':a==='unavailable'?'Nicht verfügbar':'Unbestätigt';return `<a class="provider-card" href="${x.product_url}" target="_blank" rel="noopener"><div class="provider-top"><div class="brand"><img class="brand-icon" src="${logos[x.providers.name]||'assets/icons/icon-192.svg'}" alt=""><div><h3>${x.providers.name}</h3><small>${x.providers.provider_type==='comparison'?'Vergleichsportal':'Direktanbieter'}</small></div></div><span class="badge ${a}">${label}</span></div><div class="provider-price">${euro(x.last_price)}</div><div class="provider-meta">${x.status||'Noch nicht geprüft'}<br>Aktualisiert: ${date(x.last_success_at||x.last_checked_at)}</div></a>`}).join('');fillSettings()}
async function loadHistory(){if(!sources.length)return;const since=new Date(Date.now()-days*864e5).toISOString();const ids=sources.map(x=>x.id);const {data}=await sb.from('price_history').select('price,checked_at,source_id').in('source_id',ids).eq('validated',true).gte('checked_at',since).order('checked_at');const rows=data||[];$('#chartEmpty').hidden=rows.length>0;const grouped={};rows.forEach(r=>(grouped[r.source_id]??=[]).push(r));const sets=Object.entries(grouped).map(([id,v],i)=>({label:sources.find(s=>s.id===id)?.providers.name||'Quelle',data:v.map(r=>({x:r.checked_at,y:r.price})),borderColor:['#007aff','#34c759','#ff9500','#af52de','#ff3b30','#5ac8fa'][i%6],pointRadius:1,tension:.25}));chart?.destroy();chart=new Chart($('#priceChart'),{type:'line',data:{datasets:sets},options:{responsive:true,parsing:false,plugins:{legend:{display:false}},scales:{x:{type:'category',ticks:{display:false},grid:{display:false}},y:{grid:{color:'rgba(128,128,128,.14)'}}}}})}
function fillSettings(){if(!product)return;$('#alertInput').value=product.alert_price;$('#targetInput').value=product.target_price;$('#sourceToggles').innerHTML=sources.map(s=>`<label class="toggle-row">${s.providers.name}<input class="switch" type="checkbox" data-id="${s.id}" ${s.active?'checked':''}></label>`).join('')}
async function authState(){const {data:{session}}=await sb.auth.getSession();$('#authBlock').hidden=!!session;$('#settingsContent').hidden=!session}
async function enablePush(){if(!('serviceWorker'in navigator&&'PushManager'in window)){toast('Web Push wird hier nicht unterstützt');return}if(C.vapidPublicKey.startsWith('__')){toast('VAPID-Key noch nicht eingerichtet');return}const perm=await Notification.requestPermission();if(perm!=='granted'){toast('Mitteilungen nicht erlaubt');return}const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:toBytes(C.vapidPublicKey)});const j=sub.toJSON();const {error}=await sb.from('push_subscriptions').insert({endpoint:j.endpoint,p256dh:j.keys.p256dh,auth:j.keys.auth,active:true});toast(error&&error.code!=='23505'?'Push konnte nicht gespeichert werden':'Push ist aktiviert')}
function toBytes(s){const p='='.repeat((4-s.length%4)%4),b=atob((s+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...b].map(c=>c.charCodeAt(0)))}
$('#refreshBtn').onclick=()=>load().then(()=>toast('Aktualisiert'));$('#settingsBtn').onclick=$('#settingsTab').onclick=()=>{$('#settingsDialog').showModal();authState()};$('#notifyBtn').onclick=enablePush;$('#enablePush').onclick=enablePush;
$('#loginBtn').onclick=async()=>{const email=$('#emailInput').value.trim();if(!email)return toast('E-Mail eingeben');const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:C.appBaseUrl}});toast(error?error.message:'Magic Link wurde gesendet')};
$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();authState()};$('#saveSettings').onclick=async()=>{const updates={alert_price:Number($('#alertInput').value),target_price:Number($('#targetInput').value)};let {error}=await sb.from('products').update(updates).eq('id',product.id);for(const x of $$('.switch'))await sb.from('product_sources').update({active:x.checked}).eq('id',x.dataset.id);if(error)return toast(error.message);toast('Einstellungen gespeichert');await load()};
$$('.segmented button').forEach(b=>b.onclick=()=>{$$('.segmented button').forEach(x=>x.classList.remove('active'));b.classList.add('active');days=Number(b.dataset.days);loadHistory()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');sb.auth.onAuthStateChange(()=>authState());load();
